### ISSUE TITLE
64 Bit Compliance?

### ISSUE THREAD

**Issue by holadude** [harukazepc/TiWebViewUserAgent#3]
This won't work anymore due to 64 bit compliance with apple.
logs show this: "Couldn't find module: tv.harukaze.ti.webviewuseragent.ios for architecture: x86_64"

**Comment by lasar** [comment]
The module works fine with 64bit, but needs to be recompiled (the ZIP file was never update with newer architectures).

In short (hopefully not forgetting something)
- Clone this repository
- Update `TITANIUM_SDK_VERSION` and `TITANIUM_SDK` in `iphone/titanium.xcconfig` to your versions with a text editor - I have Titanium version 3.5.0.GA
- Open `iphone/tvharukazetiwebviewuseragentios.xcodeproj` in Xcode and click on bold configuration lines named "Architecture", then hit delete to remove them - they will be replaced with default settings which will then include all architectures (instead of just the ones known to the module before)
- Go into the terminal and `cd` into the `iphone`directory.
- Execute `./build.py`

If all went well you should have a fresh file `tv.harukaze.ti.webview.useragent.ios-iphone-0.1.zip` with lib files that contain the proper architectures.

You can check this by unzipping the file and running `lipo -info modules/iphone/tv.harukaze.ti.webview.useragent.ios/0.1/libtv.harukaze.ti.webview.useragent.ios.a` which should now result in a listing containing `armv7 i386 x86_64 arm64`.

I guess I should make a pull request with these changes, but sadly don't have the time right now.

**Comment by holadude** [comment]
Thanks.  We got it working.
